language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.8"
env:
  - DJANGO_VERSION=1.8.18  # LTS supported until April 2018
  - DJANGO_VERSION=1.10.7  # supported until December 2017
  - DJANGO_VERSION=1.11.1  # LTS supported until April 2020
  - DJANGO_VERSION=2.0.5  # supported until April 2019
  - DJANGO_VERSION=3.0.4
# command to install dependencies
install: 
  - "pip install -q -e .[przelewy24,payu,moip,paymill]"
  - "pip install -q -r getpaid_test_project/requirements.txt"
  - "pip install -q Django==$DJANGO_VERSION"
  - "pip install coveralls"
# command to run tests
script:
  "cd getpaid_test_project && python manage.py test --settings=getpaid_test_project.settings_test"
after_success:
  coveralls
